export const MODELS_DATA = [
  {
    modelName: "Model 3",
    modelIcon: "../../images/model-3.png",
    paramsIcon: "../../images/tesla-3-params.png",
    iconAlt: "tesla model 3",
    params: {
      range: "334 mi",
      peakPower: "1020 hp",
      wheels: '18" or 19"',
      weight: "4048 lbs",
      battery: "Long Range",
      topSpeed: "145 mph",
    },
    price: "59490 $",
    banner: "../../images/tesla-3-banner.jpg",
  },
  {
    modelName: "Model X",
    modelIcon: "../../images/model-x.png",
    paramsIcon: "../../images/tesla-x-params.png",
    iconAlt: "tesla model X",
    params: {
      range: "333 mi",
      peakPower: "1020 hp",
      wheels: '20" or 22"',
      weight: "5390 lbs",
      topSpeed: "135 mph",
      battery: "Long Range",
    },
    price: "126490 $",
    banner: "../../images/tesla-x-banner.jpg",
  },
  {
    modelName: "Model Y",
    modelIcon: "../../images/model-Y.png",
    paramsIcon: "../../images/tesla-y-params.png",
    iconAlt: "tesla model Y",
    params: {
      range: "303mi",
      peakPower: "1020hp",
      wheels: '21"',
      weight: "4398 lbs",
      battery: "Long Range",
      topSpeed: "135 mph",
    },
    price: "67990 $",
    banner: "../../images/tesla-y-banner.jpg",
  },
  {
    modelName: "Model S",
    modelIcon: "../../images/model-S.png",
    paramsIcon: "../../images/tesla-s-params.png",
    iconAlt: "tesla model S",
    params: {
      range: "405 mi",
      peakPower: "1020 hp",
      wheels: '19" or 21"',
      weight: "4766 lbs",
      battery: "Long Range",
      topSpeed: "155 mph",
    },
    price: "109490 $",
    banner: "../../images/tesla-s-banner.jpg",
  },
];
